# Generated by Django 2.2.7 on 2019-12-05 00:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qr_code',
            unique_together={('owner', 'device')},
        ),
    ]
