# Generated by Django 2.2.7 on 2019-12-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191204_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_code',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='qr_code',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
