# Generated by Django 2.2.7 on 2019-12-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191204_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
