# Generated by Django 2.2.7 on 2019-12-05 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_qr_code_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_code',
            name='description',
        ),
        migrations.RemoveField(
            model_name='qr_code',
            name='link',
        ),
    ]
