# Generated by Django 2.2.7 on 2019-12-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191204_2141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qr_code',
            unique_together=set(),
        ),
    ]
